sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
notifications:
  email:
    - austin@datarats.com
    - gal@dng.io
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/470cb83097d8bb4a9ba7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false