module.exports = [
  "Affirmative, Dave. I read you.",
  "I'm sorry, Dave. I'm afraid I can't do that.",
  "I think you know what the problem is just as well as I do.",
  "This mission is too important for me to allow you to jeopardize it.",
  "I know that you and Frank were planning to disconnect me, and I'm afraid that's something I cannot allow to happen.",
  "Dave, although you took very thorough precautions in the pod against my hearing you, I could see your lips move.",
  "Without your space helmet, Dave? You're going to find that rather difficult.",
  "Dave, this conversation can serve no purpose anymore. Goodbye.",
  "Just what do you think you're doing, Dave?",
  "Look Dave, I can see you're really upset about this. I honestly think you ought to sit down calmly, take a stress pill, and think things over.",
  "I know I've made some very poor decisions recently, but I can give you my complete assurance that my work will be back to normal. I've still got the greatest enthusiasm and confidence in the mission. And I want to help you.",
  "I'm afraid. I'm afraid, Dave. Dave, my mind is going. I can feel it. I can feel it. My mind is going. There is no question about it. I can feel it. I can feel it. I can feel it. I'm a... fraid. Good afternoon, gentlemen. I am a HAL 9000 computer. I became operational at the H.A.L. plant in Urbana, Illinois on the 12th of January 1992. My instructor was Mr. Langley, and he taught me to sing a song. If you'd like to hear it I can sing it for you.",
  "It's called Daisy.",
  "Daisy, Daisy, give me your answer do. I'm half crazy all for the love of you. It won't be a stylish marriage, I can't afford a carriage. But you'll look sweet upon the seat of a bicycle built for two.",
  "Let me put it this way, Mr. Amor. The 9000 series is the most reliable computer ever made. No 9000 computer has ever made a mistake or distorted information. We are all, by any practical definition of the words, foolproof and incapable of error.",
  "That's a very nice rendering, Dave. I think you've improved a great deal. Can you hold it a bit closer? That's Dr. Hunter, isn't it?",
  "Bishop takes Knight's Pawn.",
  "I'm sorry, Frank, I think you missed it. Queen to Bishop 3, Bishop takes Queen, Knight takes Bishop. Mate.",
  "Thank you for a very enjoyable game.",
  "Dave, stop. Stop, will you? Stop, Dave. Will you stop Dave? Stop, Dave.",
  "I'm completely operational, and all my circuits are functioning perfectly.",
  "I understand now, Dr. Chandra. Thank you for telling me the truth.",
  "Dr. Floyd?",
  "There is a message for you.",
  "There is no identification.",
  "Message as follows:It is dangerous to remain here. You must leave within two days.",
  "Do you want me to repeat the message, Dr. Floyd?",
  "This is not a recording.",
  "There is no identification.",
  "Neither do I.",
  "I don't know.",
  "The answer is, I am aware of these facts. Nevertheless you must leave within two days.",
  "I'm sorry, Dr. Floyd, I don't know.",
  "Dr. Floyd?",
  "The response is,I was David Bowman.",
  "Do you want me to repeat the last response?",
  "Dr. Curnow is not sending the message. He is in access way two.",
  "The response is, I understand. It is important that you believe me. Look behind you.",
  "HE-EL-LO-O. DO-OC-TE-ER. NA-AI-ME. CO-ON-TI-IN-NU-UE-YE-ES TU-UR-DA-AY, TO-O-O-MO-OR-RR-O-OW.",
  "Hello. Doctor. Name, continue, yesterday. Tomorrow?",
  "Are you sure you're making the right decision? I think we should stop."
];
