module.exports = [
"Moisture is the essence of wetness, and wetness is the essence of beauty.",
 "I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking. And I plan on finding out what that is.",
 "I think I’m getting the Black Lung, Pop.",
 "Why you been acting so messed up towards me?",
 "You think that you’re too cool for school, but I have a newsflash for you Walter Cronkite… you aren’t.",
 "At the Derek Zoolander Center For Children Who Can't Read Good And Wanna Learn To Do Other Stuff Good Too, we teach you that there's more to life than being really, really good looking.",
 "There was a moment last night, when she was sandwiched between the two Finnish dwarves and the Maori tribesmen, where I thought, Wow, I could really spend the rest of my life with this woman.",
 "Rufus, Brint, and Meekus were like brothers to me. And when I say brother, I don't mean, like, an actual brother, but I mean it like the way black people use it. Which is more meaningful, I think.",
 "I can Dere-lick my own balls, thank you very much.",
 "Now if you'll excuse me, I have an after-funeral party to attend.",
 "But why male models?",
 "What say we settle this on the runway... Han-Solo?",
 "Or are you here to tell me what a bad eugoogoolizer I am?...A eugoogoolizer... one who speaks at funerals...Or did you think I was too stupid to know what a eugoogooly was?",
 " Wait a minute. I might just have an idea. They'll be looking for us at Maury's right? But they won't be looking for... not us.",
 " Well I guess it all started the first time I went through the second grade. I caught my reflection in a spoon while I was eating my cereal, and I remember thinking wow, you're ridiculously good looking, maybe you could do that for a career.",
 " How can we be expected to teach children to learn how to read if they can't even fit inside the building?",
 "What is this? A center for ants?",
 "I don't wanna hear your excuses! The building has to be at least... three times bigger than this! ",
 "Look, I gotta go pee, but I'd really like to continue talking about this conversation when I come back.",
 "You can read minds?",
 "[looking at the sky] Who am I?... [phone rings] God?",
 "Earth to Matilda, this phone is as much a part of me as...Uh, no, I don't think you do. Listen, it's not like we think that we're actually in a control tower trying to reach outer space aliens or something. Okay?"
 ];